# Generated by Django 3.2.8 on 2022-05-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno', models.IntegerField()),
                ('uname', models.CharField(max_length=30)),
                ('upass', models.CharField(max_length=16)),
                ('uemail', models.EmailField(max_length=30)),
                ('umob', models.IntegerField()),
            ],
        ),
    ]
